/**
 * Report Generation Service
 * Week 6: PDF and CSV report generation
 */

const PDFDocument = require('pdfkit');
const { Parser } = require('json2csv');

// Entomate brand colors
const BRAND = {
  primary: '#FF2D6B',     // Electric Crimson
  secondary: '#00F5D4',   // Neon Mint
  tertiary: '#FFB800',    // Amber
  dark: '#111827',        // Near-black text
  muted: '#6b7280',       // Gray text
  light: '#374151',       // Body text
  border: '#e5e7eb',      // Dividers
  success: '#10b981',
  warning: '#f59e0b',
  error: '#ef4444',
  footer: '#9ca3af',
};

class ReportService {
  /**
   * Generate a PDF meeting recap
   */
  generateMeetingRecapPDF(meeting, actionItems = []) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const chunks = [];

        doc.on('data', chunk => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        // Header
        doc.fontSize(24).fillColor(BRAND.primary).text('Meeting Recap', { align: 'center' });
        doc.moveDown(0.5);

        // Meeting title
        doc.fontSize(18).fillColor(BRAND.dark).text(meeting.title || 'Untitled Meeting');
        doc.moveDown(0.3);

        // Metadata
        doc.fontSize(10).fillColor(BRAND.muted);
        if (meeting.created_at) {
          doc.text(`Date: ${new Date(meeting.created_at).toLocaleDateString('en-US', {
            weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
          })}`);
        }
        if (meeting.duration_seconds) {
          const mins = Math.round(meeting.duration_seconds / 60);
          doc.text(`Duration: ${mins} minutes`);
        }
        doc.moveDown();

        // Divider
        doc.strokeColor(BRAND.border).lineWidth(1)
          .moveTo(50, doc.y).lineTo(545, doc.y).stroke();
        doc.moveDown();

        // Summary
        if (meeting.summary) {
          doc.fontSize(14).fillColor(BRAND.primary).text('Summary');
          doc.moveDown(0.3);
          doc.fontSize(11).fillColor(BRAND.light).text(meeting.summary, { align: 'justify' });
          doc.moveDown();
        }

        // Key Points
        if (meeting.key_points && meeting.key_points.length > 0) {
          doc.fontSize(14).fillColor(BRAND.primary).text('Key Points');
          doc.moveDown(0.3);
          meeting.key_points.forEach(point => {
            doc.fontSize(11).fillColor(BRAND.light).text(`• ${point}`, { indent: 10 });
          });
          doc.moveDown();
        }

        // Decisions
        if (meeting.decisions && meeting.decisions.length > 0) {
          doc.fontSize(14).fillColor(BRAND.primary).text('Decisions Made');
          doc.moveDown(0.3);
          meeting.decisions.forEach(decision => {
            doc.fontSize(11).fillColor(BRAND.light).text(`✓ ${decision}`, { indent: 10 });
          });
          doc.moveDown();
        }

        // Action Items
        if (actionItems.length > 0) {
          doc.fontSize(14).fillColor(BRAND.primary).text('Action Items');
          doc.moveDown(0.3);

          actionItems.forEach((item, index) => {
            const status = item.status === 'done' ? '☑' : '☐';
            const priority = item.priority ? ` [${item.priority.toUpperCase()}]` : '';
            const assignee = item.assigned_to_name ? ` → ${item.assigned_to_name}` : '';
            const dueDate = item.due_date ? ` (Due: ${new Date(item.due_date).toLocaleDateString()})` : '';

            doc.fontSize(11).fillColor(BRAND.light)
              .text(`${status} ${item.task_description}${priority}${assignee}${dueDate}`, { indent: 10 });
          });
          doc.moveDown();
        }

        // Sentiment
        if (meeting.sentiment_label) {
          doc.fontSize(12).fillColor(BRAND.muted)
            .text(`Meeting Sentiment: ${meeting.sentiment_label}`, { align: 'right' });
        }

        // Footer
        doc.moveDown(2);
        doc.fontSize(9).fillColor(BRAND.footer)
          .text(`Generated by Entomate on ${new Date().toLocaleString()}`, { align: 'center' });

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Generate a PDF goals progress report
   */
  generateGoalsReportPDF(goals, stats) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const chunks = [];

        doc.on('data', chunk => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        // Header
        doc.fontSize(24).fillColor(BRAND.primary).text('Goals & OKRs Report', { align: 'center' });
        doc.moveDown(0.5);

        // Stats summary
        if (stats) {
          doc.fontSize(12).fillColor(BRAND.light);
          doc.text(`Quarter: ${stats.quarter || 'All Time'}`, { continued: true });
          doc.text(`    Total Goals: ${stats.total || 0}`, { continued: true });
          doc.text(`    Average Progress: ${stats.averageProgress || 0}%`);
          doc.moveDown();

          // Progress bar
          const progressWidth = 300;
          const progressHeight = 20;
          const progress = stats.averageProgress || 0;

          doc.rect(50, doc.y, progressWidth, progressHeight).stroke(BRAND.border);
          doc.rect(50, doc.y, (progressWidth * progress) / 100, progressHeight)
            .fill(progress >= 70 ? BRAND.success : progress >= 40 ? BRAND.warning : BRAND.error);
          doc.moveDown(2);
        }

        // Divider
        doc.strokeColor(BRAND.border).lineWidth(1)
          .moveTo(50, doc.y).lineTo(545, doc.y).stroke();
        doc.moveDown();

        // Goals by type
        const goalTypes = ['company', 'team', 'individual'];
        goalTypes.forEach(type => {
          const typeGoals = goals.filter(g => g.goal_type === type);
          if (typeGoals.length === 0) return;

          const typeLabel = type.charAt(0).toUpperCase() + type.slice(1);
          doc.fontSize(14).fillColor(BRAND.primary).text(`${typeLabel} Goals (${typeGoals.length})`);
          doc.moveDown(0.3);

          typeGoals.forEach(goal => {
            // Goal title and progress
            doc.fontSize(12).fillColor(BRAND.dark).text(goal.title, { continued: true });
            doc.fillColor(BRAND.muted).text(` - ${goal.progress || 0}%`);

            // Status badge
            const statusColor = {
              planning: BRAND.muted,
              active: BRAND.primary,
              completed: BRAND.success,
              abandoned: BRAND.error
            };
            doc.fontSize(9).fillColor(statusColor[goal.status] || BRAND.muted)
              .text(`  Status: ${goal.status || 'planning'}`, { indent: 20 });

            // Key results
            if (goal.key_results && goal.key_results.length > 0) {
              goal.key_results.forEach(kr => {
                const krProgress = kr.target > 0 ? Math.round((kr.current / kr.target) * 100) : 0;
                doc.fontSize(10).fillColor(BRAND.light)
                  .text(`  → ${kr.title}: ${kr.current}/${kr.target} ${kr.unit || ''} (${krProgress}%)`, { indent: 30 });
              });
            }
            doc.moveDown(0.5);
          });
          doc.moveDown();
        });

        // Footer
        doc.fontSize(9).fillColor(BRAND.footer)
          .text(`Generated by Entomate on ${new Date().toLocaleString()}`, { align: 'center' });

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Generate a PDF project dashboard report
   */
  generateProjectReportPDF(project, actionItems = [], teamWorkload = []) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const chunks = [];

        doc.on('data', chunk => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        // Header
        doc.fontSize(24).fillColor(BRAND.primary).text('Project Report', { align: 'center' });
        doc.moveDown(0.5);

        // Project title
        doc.fontSize(18).fillColor(BRAND.dark).text(project.title || 'Project Overview');
        doc.moveDown(0.3);

        // Project stats
        doc.fontSize(11).fillColor(BRAND.muted);
        doc.text(`Progress: ${project.progress_percent || 0}%`);
        doc.text(`Total Items: ${project.total_items || 0}`);
        doc.text(`Completed: ${project.complete_items || 0}`);
        doc.text(`Overdue: ${project.overdue_items || 0}`);
        doc.moveDown();

        // Progress bar
        const progress = project.progress_percent || 0;
        doc.rect(50, doc.y, 300, 15).stroke(BRAND.border);
        doc.rect(50, doc.y, (300 * progress) / 100, 15)
          .fill(progress >= 70 ? BRAND.success : progress >= 40 ? BRAND.warning : BRAND.error);
        doc.moveDown(2);

        // Team Workload
        if (teamWorkload.length > 0) {
          doc.fontSize(14).fillColor(BRAND.primary).text('Team Workload');
          doc.moveDown(0.3);

          teamWorkload.forEach(member => {
            const completion = member.total_assigned > 0
              ? Math.round((member.completed_items / member.total_assigned) * 100)
              : 0;
            doc.fontSize(11).fillColor(BRAND.light)
              .text(`${member.team_member}: ${member.total_assigned} tasks (${completion}% complete)`, { indent: 10 });
          });
          doc.moveDown();
        }

        // Action Items by Status
        if (actionItems.length > 0) {
          doc.fontSize(14).fillColor(BRAND.primary).text('Action Items');
          doc.moveDown(0.3);

          const byStatus = {
            open: actionItems.filter(i => i.status === 'open'),
            in_progress: actionItems.filter(i => i.status === 'in_progress'),
            done: actionItems.filter(i => i.status === 'done')
          };

          Object.entries(byStatus).forEach(([status, items]) => {
            if (items.length === 0) return;
            const label = status.replace('_', ' ').toUpperCase();
            doc.fontSize(12).fillColor(BRAND.muted).text(`${label} (${items.length})`);

            items.slice(0, 10).forEach(item => {
              doc.fontSize(10).fillColor(BRAND.light)
                .text(`• ${item.task_description}`, { indent: 15 });
            });
            if (items.length > 10) {
              doc.fontSize(9).fillColor(BRAND.footer)
                .text(`  ... and ${items.length - 10} more`, { indent: 15 });
            }
            doc.moveDown(0.5);
          });
        }

        // Footer
        doc.moveDown();
        doc.fontSize(9).fillColor(BRAND.footer)
          .text(`Generated by Entomate on ${new Date().toLocaleString()}`, { align: 'center' });

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Generate CSV export for meetings
   */
  generateMeetingsCSV(meetings) {
    const fields = [
      { label: 'ID', value: 'id' },
      { label: 'Title', value: 'title' },
      { label: 'Date', value: row => row.created_at ? new Date(row.created_at).toLocaleDateString() : '' },
      { label: 'Duration (min)', value: row => row.duration_seconds ? Math.round(row.duration_seconds / 60) : '' },
      { label: 'Summary', value: 'summary' },
      { label: 'Sentiment', value: 'sentiment_label' },
      { label: 'Sentiment Score', value: 'sentiment_score' }
    ];

    const parser = new Parser({ fields });
    return parser.parse(meetings);
  }

  /**
   * Generate CSV export for action items
   */
  generateActionItemsCSV(actionItems) {
    const fields = [
      { label: 'ID', value: 'id' },
      { label: 'Task', value: 'task_description' },
      { label: 'Status', value: 'status' },
      { label: 'Priority', value: 'priority' },
      { label: 'Assigned To', value: 'assigned_to_name' },
      { label: 'Email', value: 'assigned_to_email' },
      { label: 'Due Date', value: row => row.due_date ? new Date(row.due_date).toLocaleDateString() : '' },
      { label: 'Created', value: row => row.created_at ? new Date(row.created_at).toLocaleDateString() : '' },
      { label: 'Completed', value: row => row.completed_at ? new Date(row.completed_at).toLocaleDateString() : '' }
    ];

    const parser = new Parser({ fields });
    return parser.parse(actionItems);
  }

  /**
   * Generate CSV export for goals
   */
  generateGoalsCSV(goals) {
    const fields = [
      { label: 'ID', value: 'id' },
      { label: 'Title', value: 'title' },
      { label: 'Type', value: 'goal_type' },
      { label: 'Status', value: 'status' },
      { label: 'Progress', value: row => `${row.progress || 0}%` },
      { label: 'Quarter', value: 'quarter' },
      { label: 'Key Results', value: row => (row.key_results || []).length },
      { label: 'Start Date', value: row => row.start_date ? new Date(row.start_date).toLocaleDateString() : '' },
      { label: 'Target Date', value: row => row.target_date ? new Date(row.target_date).toLocaleDateString() : '' }
    ];

    const parser = new Parser({ fields });
    return parser.parse(goals);
  }

  /**
   * Generate CSV export for tasks
   */
  generateTasksCSV(tasks) {
    const fields = [
      { label: 'ID', value: 'id' },
      { label: 'Title', value: 'title' },
      { label: 'Description', value: 'description' },
      { label: 'Status', value: 'status' },
      { label: 'Priority', value: 'priority' },
      { label: 'Assigned To', value: 'assigned_to' },
      { label: 'Project ID', value: 'project_id' },
      { label: 'Due Date', value: row => row.due_date ? new Date(row.due_date).toLocaleDateString() : '' },
      { label: 'Start Date', value: row => row.start_date ? new Date(row.start_date).toLocaleDateString() : '' },
      { label: 'Tags', value: row => (row.tags || []).join(', ') },
      { label: 'Created', value: row => row.created_at ? new Date(row.created_at).toLocaleDateString() : '' },
      { label: 'Completed', value: row => row.completed_at ? new Date(row.completed_at).toLocaleDateString() : '' }
    ];

    const parser = new Parser({ fields });
    return parser.parse(tasks);
  }

  /**
   * Generate a weekly summary report
   */
  generateWeeklySummaryPDF(data) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const chunks = [];

        doc.on('data', chunk => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        const { meetings, actionItems, goals, period } = data;

        // Header
        doc.fontSize(24).fillColor(BRAND.primary).text('Weekly Summary Report', { align: 'center' });
        doc.moveDown(0.3);
        doc.fontSize(12).fillColor(BRAND.muted).text(period || 'This Week', { align: 'center' });
        doc.moveDown();

        // Quick Stats
        doc.fontSize(14).fillColor(BRAND.primary).text('Quick Stats');
        doc.moveDown(0.3);

        const stats = [
          `Meetings Held: ${meetings?.length || 0}`,
          `Action Items Created: ${actionItems?.filter(i => i.status !== 'done').length || 0}`,
          `Action Items Completed: ${actionItems?.filter(i => i.status === 'done').length || 0}`,
          `Active Goals: ${goals?.filter(g => g.status === 'active').length || 0}`
        ];

        stats.forEach(stat => {
          doc.fontSize(11).fillColor(BRAND.light).text(`• ${stat}`, { indent: 10 });
        });
        doc.moveDown();

        // Meetings Summary
        if (meetings && meetings.length > 0) {
          doc.fontSize(14).fillColor(BRAND.primary).text('Meetings');
          doc.moveDown(0.3);

          meetings.slice(0, 5).forEach(meeting => {
            doc.fontSize(11).fillColor(BRAND.dark).text(meeting.title || 'Untitled');
            if (meeting.summary) {
              doc.fontSize(10).fillColor(BRAND.muted)
                .text(meeting.summary.substring(0, 150) + (meeting.summary.length > 150 ? '...' : ''), { indent: 10 });
            }
            doc.moveDown(0.3);
          });
          doc.moveDown();
        }

        // Overdue Items
        const overdueItems = actionItems?.filter(i =>
          i.due_date && new Date(i.due_date) < new Date() && i.status !== 'done'
        ) || [];

        if (overdueItems.length > 0) {
          doc.fontSize(14).fillColor(BRAND.error).text(`⚠ Overdue Items (${overdueItems.length})`);
          doc.moveDown(0.3);

          overdueItems.slice(0, 5).forEach(item => {
            doc.fontSize(10).fillColor(BRAND.light)
              .text(`• ${item.task_description}`, { indent: 10 });
          });
          doc.moveDown();
        }

        // Footer
        doc.moveDown();
        doc.fontSize(9).fillColor(BRAND.footer)
          .text(`Generated by Entomate on ${new Date().toLocaleString()}`, { align: 'center' });

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }
}

module.exports = new ReportService();
